'hse strict';function m(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var r=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function v(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var w=v(this);function x(a,b){if(b)a:{var c=w;a=a.split(".");for(var e=0;e<a.length-1;e++){var g=a[e];if(!(g in c))break a;c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&r(c,a,{configurable:!0,writable:!0,value:b})}}
x("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(e+(k||"")+"_"+g++,k)}function c(k,d){this.$jscomp$symbol$id_=k;r(this,"description",{configurable:!0,writable:!0,value:d})}if(a)return a;c.prototype.toString=function(){return this.$jscomp$symbol$id_};var e="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",g=0;return b});
x("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var e=w[b[c]];typeof e==="function"&&typeof e.prototype[a]!="function"&&r(e.prototype,a,{configurable:!0,writable:!0,value:function(){return y(m(this))}})}return a});function y(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function z(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:m(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function A(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.abruptCompletion_=null}function B(a){if(a.isRunning_)throw new TypeError("Generator is already running");a.isRunning_=!0}
A.prototype.JSC$3751_next_=function(a){this.yieldResult=a};function C(a,b){a.abruptCompletion_={exception:b,isException:!0};a.nextAddress=a.catchAddress_||a.finallyAddress_}A.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};function D(a,b,c){a.nextAddress=c;return{value:b}}function E(a){a.catchAddress_=0;var b=a.abruptCompletion_.exception;a.abruptCompletion_=null;return b}function F(a){this.context_=new A;this.program_=a}
function H(a,b){B(a.context_);var c=a.context_.yieldAllIterator_;if(c)return I(a,"return"in c?c["return"]:function(e){return{value:e,done:!0}},b,a.context_.return);a.context_.return(b);return J(a)}
function I(a,b,c,e){try{var g=b.call(a.context_.yieldAllIterator_,c);if(!(g instanceof Object))throw new TypeError("Iterator result "+g+" is not an object");if(!g.done)return a.context_.isRunning_=!1,g;var k=g.value}catch(d){return a.context_.yieldAllIterator_=null,C(a.context_,d),J(a)}a.context_.yieldAllIterator_=null;e.call(a.context_,k);return J(a)}
function J(a){for(;a.context_.nextAddress;)try{var b=a.program_(a.context_);if(b)return a.context_.isRunning_=!1,{value:b.value,done:!1}}catch(c){a.context_.yieldResult=void 0,C(a.context_,c)}a.context_.isRunning_=!1;if(a.context_.abruptCompletion_){b=a.context_.abruptCompletion_;a.context_.abruptCompletion_=null;if(b.isException)throw b.exception;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function K(a){this.next=function(b){B(a.context_);a.context_.yieldAllIterator_?b=I(a,a.context_.yieldAllIterator_.next,b,a.context_.JSC$3751_next_):(a.context_.JSC$3751_next_(b),b=J(a));return b};this.throw=function(b){B(a.context_);a.context_.yieldAllIterator_?b=I(a,a.context_.yieldAllIterator_["throw"],b,a.context_.JSC$3751_next_):(C(a.context_,b),b=J(a));return b};this.return=function(b){return H(a,b)};this[Symbol.iterator]=function(){return this}}
function L(a){function b(e){return a.next(e)}function c(e){return a.throw(e)}return new Promise(function(e,g){function k(d){d.done?e(d.value):Promise.resolve(d.value).then(b,c).then(k,g)}k(a.next())})}function M(a){return L(new K(new F(a)))}
x("Promise",function(a){function b(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var f=this.createResolveAndReject_();try{d(f.resolve,f.reject)}catch(h){f.reject(h)}}function c(){this.batch_=null}function e(d){return d instanceof b?d:new b(function(f){f(d)})}if(a)return a;c.prototype.asyncExecute=function(d){if(this.batch_==null){this.batch_=[];var f=this;this.asyncExecuteFunction(function(){f.executeBatch_()})}this.batch_.push(d)};var g=w.setTimeout;
c.prototype.asyncExecuteFunction=function(d){g(d,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var f=0;f<d.length;++f){var h=d[f];d[f]=null;try{h()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};c.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};b.prototype.createResolveAndReject_=function(){function d(l){return function(n){h||(h=!0,l.call(f,n))}}var f=this,h=!1;return{resolve:d(this.resolveTo_),
reject:d(this.reject_)}};b.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof b)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var f=d!=null;break a;case "function":f=!0;break a;default:f=!1}f?this.resolveToNonPromiseObj_(d):this.fulfill_(d)}};b.prototype.resolveToNonPromiseObj_=function(d){var f=void 0;try{f=d.then}catch(h){this.reject_(h);return}typeof f=="function"?this.settleSameAsThenable_(f,
d):this.fulfill_(d)};b.prototype.reject_=function(d){this.settle_(2,d)};b.prototype.fulfill_=function(d){this.settle_(1,d)};b.prototype.settle_=function(d,f){if(this.state_!=0)throw Error("Cannot settle("+d+", "+f+"): Promise already settled in state"+this.state_);this.state_=d;this.result_=f;this.state_===2&&this.scheduleUnhandledRejectionCheck_();this.executeOnSettledCallbacks_()};b.prototype.scheduleUnhandledRejectionCheck_=function(){var d=this;g(function(){if(d.notifyUnhandledRejection_()){var f=
w.console;typeof f!=="undefined"&&f.error(d.result_)}},1)};b.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var d=w.CustomEvent,f=w.Event,h=w.dispatchEvent;if(typeof h==="undefined")return!0;typeof d==="function"?d=new d("unhandledrejection",{cancelable:!0}):typeof f==="function"?d=new f("unhandledrejection",{cancelable:!0}):(d=w.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.result_;return h(d)};
b.prototype.executeOnSettledCallbacks_=function(){if(this.onSettledCallbacks_!=null){for(var d=0;d<this.onSettledCallbacks_.length;++d)k.asyncExecute(this.onSettledCallbacks_[d]);this.onSettledCallbacks_=null}};var k=new c;b.prototype.settleSameAsPromise_=function(d){var f=this.createResolveAndReject_();d.callWhenSettled_(f.resolve,f.reject)};b.prototype.settleSameAsThenable_=function(d,f){var h=this.createResolveAndReject_();try{d.call(f,h.resolve,h.reject)}catch(l){h.reject(l)}};b.prototype.then=
function(d,f){function h(p,t){return typeof p=="function"?function(q){try{l(p(q))}catch(G){n(G)}}:t}var l,n,u=new b(function(p,t){l=p;n=t});this.callWhenSettled_(h(d,l),h(f,n));return u};b.prototype.catch=function(d){return this.then(void 0,d)};b.prototype.callWhenSettled_=function(d,f){function h(){switch(l.state_){case 1:d(l.result_);break;case 2:f(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;this.onSettledCallbacks_==null?k.asyncExecute(h):this.onSettledCallbacks_.push(h);
this.isRejectionHandled_=!0};b.resolve=e;b.reject=function(d){return new b(function(f,h){h(d)})};b.race=function(d){return new b(function(f,h){for(var l=z(d),n=l.next();!n.done;n=l.next())e(n.value).callWhenSettled_(f,h)})};b.all=function(d){var f=z(d),h=f.next();return h.done?e([]):new b(function(l,n){function u(q){return function(G){p[q]=G;t--;t==0&&l(p)}}var p=[],t=0;do p.push(void 0),t++,e(h.value).callWhenSettled_(u(p.length-1),n),h=f.next();while(!h.done)})};return b});
x("Object.entries",function(a){return a?a:function(b){var c=[],e;for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&c.push([e,b[e]]);return c}});x("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});x("Array.prototype.includes",function(a){return a?a:function(b,c){var e=this;e instanceof String&&(e=String(e));var g=e.length;c=c||0;for(c<0&&(c=Math.max(c+g,0));c<g;c++){var k=e[c];if(k===b||Object.is(k,b))return!0}return!1}});
x("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});function N(a,b,c){if(typeof a==="object"&&typeof b==="string"){var e=a;a=b}else if(typeof a==="string"&&typeof b==="function")c=b;else return{lang:"",isValid:!1};return{lang:a,callback:c,requestor:e,isValid:!0}}function O(a){return M(function(b){return b.nextAddress==1?D(b,a.JSC$3785_chrome.offscreen.hasDocument(),2):b.return(b.yieldResult)})}
function P(a){var b,c;return M(function(e){switch(e.nextAddress){case 1:return D(e,O(a),2);case 2:if(b=e.yieldResult)return e.return();e.catchAddress_=3;return D(e,a.JSC$3785_chrome.offscreen.createDocument({url:"offscreen.html",reasons:[a.JSC$3785_chrome.offscreen.Reason.AUDIO_PLAYBACK,a.JSC$3785_chrome.offscreen.Reason.USER_MEDIA],justification:"Required for Text-to-Speech audio synthesis and playback"}),5);case 5:e.nextAddress=0;e.catchAddress_=0;break;case 3:c=E(e),console.error("Failed to create offscreen document:",
c),e.nextAddress=0}})}function Q(){var a=R;return M(function(b){if(b.nextAddress==1)return D(b,O(a),2);if(b.nextAddress!=3)return b.yieldResult?D(b,a.JSC$3785_chrome.offscreen.closeDocument(),3):b.return();b.nextAddress=0})}function S(){var a=R,b;return M(function(c){if(c.nextAddress==1)return c.catchAddress_=2,D(c,P(a),4);if(c.nextAddress!=2)return c.return(!0);b=E(c);console.error("Error ensuring offscreen document is ready:",b);return c.return(!1)})};var R=new function(){var a=this;this.JSC$3785_chrome=chrome;this.handleOnSpeak=function(b,c,e){var g,k,d;return M(function(f){if(f.nextAddress==1)return a.ttsEventCallback=e,g={type:"speak",utterance:b,options:c},f.catchAddress_=2,D(f,a.JSC$3785_chrome.runtime.sendMessage(g),4);f.nextAddress!=2?(f.nextAddress=0,f.catchAddress_=0):(k=E(f),d=k instanceof Error?k.message:"Error while trying to speak.",e({type:"error",errorMessage:d}),f.nextAddress=0)})};this.handleOnStop=function(){var b;return M(function(c){a.ttsEventCallback=
void 0;b={type:"stop"};return D(c,a.JSC$3785_chrome.runtime.sendMessage(b),0)})};this.handleOnPause=function(){var b;return M(function(c){b={type:"pause"};return D(c,a.JSC$3785_chrome.runtime.sendMessage(b),0)})};this.handleOnResume=function(){var b;return M(function(c){b={type:"resume"};return D(c,a.JSC$3785_chrome.runtime.sendMessage(b),0)})};this.handleOnInstallLanguageRequest=function(b,c,e){var g,k,d,f,h,l,n,u,p,t;return M(function(q){if(q.nextAddress==1){g=N(b,c,e);k=g.lang;d=g.requestor;f=
g.isValid;n=(l=(h=d)==null?void 0:h.source)!=null?l:"unknown";if(!f||n!==a.expectedSource)return q.return();u={type:"installLanguage",lang:k};return D(q,a.JSC$3785_chrome.runtime.sendMessage(u),2)}p=q.yieldResult;t={lang:p.lang,installStatus:p.status};a.JSC$3785_chrome.ttsEngine.updateLanguage(t);q.nextAddress=0})};this.handleOnLanguageStatusRequest=function(b,c,e){var g,k,d,f,h,l,n,u,p,t;return M(function(q){if(q.nextAddress==1){g=N(b,c,e);k=g.lang;d=g.requestor;f=g.isValid;n=(l=(h=d)==null?void 0:
h.source)!=null?l:"unknown";if(!f||n!==a.expectedSource)return q.return();u={type:"getLanguageStatus",lang:k};return D(q,a.JSC$3785_chrome.runtime.sendMessage(u),2)}p=q.yieldResult;t={lang:p.lang,installStatus:p.status};a.JSC$3785_chrome.ttsEngine.updateLanguage(t);q.nextAddress=0})};this.handleOnUninstallLanguageRequest=function(b,c){var e;return M(function(g){if(b.source!==a.expectedSource)return g.return();e={type:"uninstallLanguage",lang:c};return D(g,a.JSC$3785_chrome.runtime.sendMessage(e),
0)})};this.expectedSource=this.JSC$3785_chrome.ttsEngine.TtsClientSource.CHROMEFEATURE;this.JSC$3785_chrome.runtime.onInstalled.addListener(function(){return M(function(b){return D(b,P(a),0)})});this.JSC$3785_chrome.ttsEngine.onSpeak.addListener(this.handleOnSpeak);this.JSC$3785_chrome.ttsEngine.onStop.addListener(this.handleOnStop);this.JSC$3785_chrome.ttsEngine.onPause.addListener(this.handleOnPause);this.JSC$3785_chrome.ttsEngine.onResume.addListener(this.handleOnResume);this.JSC$3785_chrome.ttsEngine.onInstallLanguageRequest.addListener(this.handleOnInstallLanguageRequest);
this.JSC$3785_chrome.ttsEngine.onLanguageStatusRequest.addListener(this.handleOnLanguageStatusRequest);this.JSC$3785_chrome.ttsEngine.onUninstallLanguageRequest.addListener(this.handleOnUninstallLanguageRequest)};
(function(){var a,b;M(function(c){if(c.nextAddress==1)return D(c,S(),2);if(c.nextAddress!=3){if(!c.yieldResult)return c.return();console.log("Ensured Offscreen Ready!");a={type:"do-task",taskData:{someValue:"hello from background"}};return D(c,R.JSC$3785_chrome.runtime.sendMessage(a),3)}b=c.yieldResult;console.log("Task response",b);b.result&&b.result.includes("close")?c=D(c,Q(),0):(c.nextAddress=0,c=void 0);return c})})();
chrome.runtime.onMessage.addListener(function(a){if(a.type==="offscreenVoicesResponse"){var b=R,c=[];a=z(Object.entries(a.voices));for(var e=a.next();!e.done;e=a.next()){var g=z(e.value);e=g.next().value;g=g.next().value;g=z(g);for(var k=g.next();!k.done;k=g.next())c.push({lang:e,voiceName:k.value,eventTypes:["start","end","error","word"]})}b.JSC$3785_chrome.ttsEngine.updateVoices(c)}return!0});
chrome.runtime.onMessage.addListener(function(a){if(a.type==="offscreenTtsEventResponse"){var b=R;b.ttsEventCallback&&b.ttsEventCallback(a.event)}return!0});
