'use strict';var aa;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ca=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function l(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ca(c,a,{configurable:!0,writable:!0,value:b})}}
l("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.$jscomp$symbol$id_=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.$jscomp$symbol$id_};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
l("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(ba(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var ha=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ia;if(typeof Object.setPrototypeOf=="function")ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ma=ia;
function p(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(ma)ma(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype}function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}
function na(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.abruptCompletion_=null}function oa(a){if(a.isRunning_)throw new TypeError("Generator is already running");a.isRunning_=!0}na.prototype.JSC$3779_next_=function(a){this.yieldResult=a};function pa(a,b){a.abruptCompletion_={exception:b,isException:!0};a.nextAddress=a.catchAddress_||a.finallyAddress_}
na.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};function r(a,b,c){a.nextAddress=c;return{value:b}}function qa(a){a.catchAddress_=0;var b=a.abruptCompletion_.exception;a.abruptCompletion_=null;return b}function ra(a){this.context_=new na;this.program_=a}
function sa(a,b){oa(a.context_);var c=a.context_.yieldAllIterator_;if(c)return ta(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.context_.return);a.context_.return(b);return ua(a)}
function ta(a,b,c,d){try{var e=b.call(a.context_.yieldAllIterator_,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.context_.isRunning_=!1,e;var f=e.value}catch(g){return a.context_.yieldAllIterator_=null,pa(a.context_,g),ua(a)}a.context_.yieldAllIterator_=null;d.call(a.context_,f);return ua(a)}
function ua(a){for(;a.context_.nextAddress;)try{var b=a.program_(a.context_);if(b)return a.context_.isRunning_=!1,{value:b.value,done:!1}}catch(c){a.context_.yieldResult=void 0,pa(a.context_,c)}a.context_.isRunning_=!1;if(a.context_.abruptCompletion_){b=a.context_.abruptCompletion_;a.context_.abruptCompletion_=null;if(b.isException)throw b.exception;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function va(a){this.next=function(b){oa(a.context_);a.context_.yieldAllIterator_?b=ta(a,a.context_.yieldAllIterator_.next,b,a.context_.JSC$3779_next_):(a.context_.JSC$3779_next_(b),b=ua(a));return b};this.throw=function(b){oa(a.context_);a.context_.yieldAllIterator_?b=ta(a,a.context_.yieldAllIterator_["throw"],b,a.context_.JSC$3779_next_):(pa(a.context_,b),b=ua(a));return b};this.return=function(b){return sa(a,b)};this[Symbol.iterator]=function(){return this}}
function wa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}function t(a){return wa(new va(new ra(a)))}l("Reflect.setPrototypeOf",function(a){return a?a:ma?function(b,c){try{return ma(b,c),!0}catch(d){return!1}}:null});
l("Promise",function(a){function b(g){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var h=this.createResolveAndReject_();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.batch_=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.asyncExecute=function(g){if(this.batch_==null){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(g)};var e=ea.setTimeout;
c.prototype.asyncExecuteFunction=function(g){e(g,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var g=this.batch_;this.batch_=[];for(var h=0;h<g.length;++h){var k=g[h];g[h]=null;try{k()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};c.prototype.asyncThrow_=function(g){this.asyncExecuteFunction(function(){throw g;})};b.prototype.createResolveAndReject_=function(){function g(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:g(this.resolveTo_),
reject:g(this.reject_)}};b.prototype.resolveTo_=function(g){if(g===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.settleSameAsPromise_(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(g):this.fulfill_(g)}};b.prototype.resolveToNonPromiseObj_=function(g){var h=void 0;try{h=g.then}catch(k){this.reject_(k);return}typeof h=="function"?this.settleSameAsThenable_(h,
g):this.fulfill_(g)};b.prototype.reject_=function(g){this.settle_(2,g)};b.prototype.fulfill_=function(g){this.settle_(1,g)};b.prototype.settle_=function(g,h){if(this.state_!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.state_);this.state_=g;this.result_=h;this.state_===2&&this.scheduleUnhandledRejectionCheck_();this.executeOnSettledCallbacks_()};b.prototype.scheduleUnhandledRejectionCheck_=function(){var g=this;e(function(){if(g.notifyUnhandledRejection_()){var h=
ea.console;typeof h!=="undefined"&&h.error(g.result_)}},1)};b.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var g=ea.CustomEvent,h=ea.Event,k=ea.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=ea.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.result_;return k(g)};
b.prototype.executeOnSettledCallbacks_=function(){if(this.onSettledCallbacks_!=null){for(var g=0;g<this.onSettledCallbacks_.length;++g)f.asyncExecute(this.onSettledCallbacks_[g]);this.onSettledCallbacks_=null}};var f=new c;b.prototype.settleSameAsPromise_=function(g){var h=this.createResolveAndReject_();g.callWhenSettled_(h.resolve,h.reject)};b.prototype.settleSameAsThenable_=function(g,h){var k=this.createResolveAndReject_();try{g.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=
function(g,h){function k(v,z){return typeof v=="function"?function(H){try{m(v(H))}catch(D){n(D)}}:z}var m,n,w=new b(function(v,z){m=v;n=z});this.callWhenSettled_(k(g,m),k(h,n));return w};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.callWhenSettled_=function(g,h){function k(){switch(m.state_){case 1:g(m.result_);break;case 2:h(m.result_);break;default:throw Error("Unexpected state: "+m.state_);}}var m=this;this.onSettledCallbacks_==null?f.asyncExecute(k):this.onSettledCallbacks_.push(k);
this.isRejectionHandled_=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var m=q(g),n=m.next();!n.done;n=m.next())d(n.value).callWhenSettled_(h,k)})};b.all=function(g){var h=q(g),k=h.next();return k.done?d([]):new b(function(m,n){function w(H){return function(D){v[H]=D;z--;z==0&&m(v)}}var v=[],z=0;do v.push(void 0),z++,d(k.value).callWhenSettled_(w(v.length-1),n),k=h.next();while(!k.done)})};return b});
l("Object.setPrototypeOf",function(a){return a||ma});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var xa=typeof Object.assign=="function"?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};l("Object.assign",function(a){return a||xa});
l("WeakMap",function(a){function b(k){this.id_=(h+=Math.random()+1).toString();if(k){k=q(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function e(k){if(!u(k,g)){var m=new c;ca(k,g,{value:m})}}function f(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(w){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.id_]=m;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.id_]:void 0};b.prototype.has=function(k){return d(k)&&
u(k,g)&&u(k[g],this.id_)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.id_)?delete k[g][this.id_]:!1};return b});
l("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,k){var m=h[1];return fa(function(){if(m){for(;m.head!=h[1];)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function d(h,k){var m=k&&typeof k;m=="object"||m=="function"?f.has(k)?m=f.get(k):(m=""+ ++g,f.set(k,m)):m="p_"+k;var n=h[0][m];if(n&&u(h[0],m))for(h=0;h<n.length;h++){var w=n[h];if(k!==k&&w.key!==w.key||k===w.key)return{id:m,list:n,index:h,entry:w}}return{id:m,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!m.next().done?!1:!0}catch(w){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:k},m.list.push(m.entry),this[1].previous.next=m.entry,this[1].previous=m.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
l("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});
l("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});l("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});l("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});l("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});l("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
l("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
l("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
function ya(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}l("Array.prototype.entries",function(a){return a?a:function(){return ya(this,function(b,c){return[b,c]})}});l("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});
l("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var za=this||self;function Aa(a){return a};function Ba(){return typeof BigInt==="function"};var Ca=typeof za.BigInt==="function"&&typeof za.BigInt(0)==="bigint";var Da=Number.MIN_SAFE_INTEGER.toString(),Ea=Ca?BigInt(Number.MIN_SAFE_INTEGER):void 0,Fa=Number.MAX_SAFE_INTEGER.toString(),Ga=Ca?BigInt(Number.MAX_SAFE_INTEGER):void 0;function Ha(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Ia=typeof Uint8Array.prototype.slice==="function",x=0,y=0,Ja;function Ka(a){var b=a>>>0;x=b;y=(a-b)/4294967296>>>0}function La(a){if(a<0){Ka(-a);var b=q(Ma(x,y));a=b.next().value;b=b.next().value;x=a>>>0;y=b>>>0}else Ka(a)}function Na(a){var b=Ja||(Ja=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);y=0;x=b.getUint32(0,!0)}function Oa(a){var b=Ja||(Ja=new DataView(new ArrayBuffer(8)));b.setFloat64(0,+a,!0);x=b.getUint32(0,!0);y=b.getUint32(4,!0)}
function Pa(a,b){var c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:Qa(a,b)}function Ra(a,b){var c=b&2147483648;c&&(a=~a+1>>>0,b=~b>>>0,a==0&&(b=b+1>>>0));a=Pa(a,b);return typeof a==="number"?c?-a:a:c?"-"+a:a}
function Qa(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Ba()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+Sa(c)+Sa(a));return c}function Sa(a){a=String(a);return"0000000".slice(a.length)+a}
function Ta(a){if(a.length<16)La(Number(a));else if(Ba())a=BigInt(a),x=Number(a&BigInt(4294967295))>>>0,y=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");y=x=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),y*=1E6,x=x*1E6+d,x>=4294967296&&(y+=Math.trunc(x/4294967296),y>>>=0,x>>>=0);b&&(b=q(Ma(x,y)),a=b.next().value,b=b.next().value,x=a,y=b)}}function Ma(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function Ua(a,b){this.JSC$3835_lo=a>>>0;this.JSC$3835_hi=b>>>0}function Va(a){return a.JSC$3835_lo===0?new Ua(0,1+~a.JSC$3835_hi):new Ua(~a.JSC$3835_lo+1,~a.JSC$3835_hi)}function Wa(a){a=BigInt.asUintN(64,a);return new Ua(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}function Xa(a){if(!a)return Ya||(Ya=new Ua(0,0));if(!/^\d+$/.test(a))return null;Ta(a);return new Ua(x,y)}var Ya;function Za(a,b){this.JSC$3838_lo=a>>>0;this.JSC$3838_hi=b>>>0}
function $a(a){a=BigInt.asUintN(64,a);return new Za(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}function ab(a){if(!a)return bb||(bb=new Za(0,0));if(!/^-?\d+$/.test(a))return null;Ta(a);return new Za(x,y)}var bb;function cb(a,b){return Error("Invalid wire type: "+a+" (at position "+b+")")}function db(){return Error("Failed to read varint, encoding is invalid.")}function eb(a,b){return Error("Tried to read past the end of the data "+b+" > "+a)};function fb(){throw Error("Invalid UTF8");}function gb(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b}var hb=void 0,ib,jb=typeof TextDecoder!=="undefined",kb,lb=typeof String.prototype.isWellFormed==="function",mb=typeof TextEncoder!=="undefined";
function nb(a){var b=!1;b=b===void 0?!1:b;if(mb){if(b&&(lb?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("Found an unpaired surrogate");a=(kb||(kb=new TextEncoder)).encode(a)}else{for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(f<128)d[c++]=f;else{if(f<2048)d[c++]=f>>6|192;else{if(f>=55296&&f<=57343){if(f<=56319&&e<a.length){var g=a.charCodeAt(++e);if(g>=56320&&g<=57343){f=(f-55296)*1024+g-56320+
65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=c===d.length?d:d.subarray(0,c)}return a};function ob(a){za.setTimeout(function(){throw a;},0)};var pb,qb;a:{for(var rb=["CLOSURE_FLAGS"],sb=za,tb=0;tb<rb.length;tb++)if(sb=sb[rb[tb]],sb==null){qb=null;break a}qb=sb}var ub=qb&&qb[610401301];pb=ub!=null?ub:!1;function vb(){var a=za.navigator;return a&&(a=a.userAgent)?a:""}var wb,xb=za.navigator;wb=xb?xb.userAgentData||null:null;var yb={},zb=null;function Ab(a){var b=a.length,c=b*3/4;c%3?c=Math.floor(c):"=.".indexOf(a[b-1])!=-1&&(c="=.".indexOf(a[b-2])!=-1?c-2:c-1);var d=new Uint8Array(c),e=0;Bb(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function Bb(a,b){function c(k){for(;d<a.length;){var m=a.charAt(d++),n=zb[m];if(n!=null)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return k}Cb();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(h===64&&e===-1)break;b(e<<2|f>>4);g!=64&&(b(f<<4&240|g>>2),h!=64&&b(g<<6&192|h))}}
function Cb(){if(!zb){zb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;c<5;c++){var d=a.concat(b[c].split(""));yb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];zb[f]===void 0&&(zb[f]=e)}}}};var Db=typeof Uint8Array!=="undefined",Eb=!(pb&&wb&&wb.brands.length>0?0:vb().indexOf("Trident")!=-1||vb().indexOf("MSIE")!=-1)&&typeof btoa==="function",Fb=/[-_.]/g,Gb={"-":"+",_:"/",".":"="};function Hb(a){return Gb[a]||""}function Ib(a){if(!Eb)return Ab(a);a=Fb.test(a)?a.replace(Fb,Hb):a;a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Jb={};function Kb(a,b){Lb(b);this.JSC$3853_value_=a;if(a!=null&&a.length===0)throw Error("ByteString should be constructed with non-empty values");}function Mb(){return Nb||(Nb=new Kb(null,Jb))}function Ob(a){Lb(Jb);var b=a.JSC$3853_value_;b=b==null||Db&&b!=null&&b instanceof Uint8Array?b:typeof b==="string"?Ib(b):null;return b==null?b:a.JSC$3853_value_=b}var Nb;function Lb(a){if(a!==Jb)throw Error("illegal external caller");};function Pb(a,b,c){this.buffer=a;if(c&&!b)throw Error();this.JSC$6237_isImmutable=b}
function Qb(a,b){if(typeof a==="string")return new Pb(Ib(a),b);if(Array.isArray(a))return new Pb(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new Pb(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new Pb(a,!1);if(a.constructor===Kb)return b=Ob(a)||new Uint8Array(0),new Pb(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new Pb(a,!1);throw Error();};function Rb(a,b,c,d){this.bytes_=null;this.bytesAreImmutable_=!1;this.cursor_=this.end_=this.JSC$3860_start_=0;this.init(a,b,c,d)}
Rb.prototype.init=function(a,b,c,d){var e=d===void 0?{}:d;d=e.aliasBytesFields===void 0?!1:e.aliasBytesFields;e=e.treatNewDataAsImmutable===void 0?!1:e.treatNewDataAsImmutable;this.aliasBytesFields=d;this.treatNewDataAsImmutable=e;a&&(a=Qb(a,this.treatNewDataAsImmutable),this.bytes_=a.buffer,this.bytesAreImmutable_=a.JSC$6237_isImmutable,this.JSC$3860_start_=b||0,this.end_=c!==void 0?this.JSC$3860_start_+c:this.bytes_.length,this.cursor_=this.JSC$3860_start_)};
Rb.prototype.clear=function(){this.bytes_=null;this.bytesAreImmutable_=!1;this.cursor_=this.end_=this.JSC$3860_start_=0;this.aliasBytesFields=!1};function Sb(a,b){var c=0,d=0,e=0,f=a.bytes_,g=a.cursor_;do{var h=f[g++];c|=(h&127)<<e;e+=7}while(e<32&&h&128);e>32&&(d|=(h&127)>>4);for(e=3;e<32&&h&128;e+=7)h=f[g++],d|=(h&127)<<e;Tb(a,g);if(h<128)return b(c>>>0,d>>>0);throw db();}function Tb(a,b){a.cursor_=b;if(b>a.end_)throw eb(a.end_,b);}
function Ub(a){var b=a.bytes_,c=a.cursor_,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw db();Tb(a,c);return e}function Vb(a){return Ub(a)>>>0}function Wb(a){a=Vb(a);return a>>>1^-(a&1)}function Xb(a){return Sb(a,Ra)}
function Yb(a){var b=a.bytes_,c=a.cursor_,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];Tb(a,a.cursor_+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}function Zb(a){var b=Yb(a);a=(b>>31)*2+1;var c=b>>>23&255;b&=8388607;return c==255?b?NaN:a*Infinity:c==0?a*1.401298464324817E-45*b:a*Math.pow(2,c-150)*(b+8388608)}function $b(a){var b=Yb(a),c=Yb(a);a=(c>>31)*2+1;var d=c>>>20&2047;b=4294967296*(c&1048575)+b;return d==2047?b?NaN:a*Infinity:d==0?a*4.9E-324*b:a*Math.pow(2,d-1075)*(b+4503599627370496)}
function ac(a){for(var b=0,c=a.cursor_,d=c+10,e=a.bytes_;c<d;){var f=e[c++];b|=f;if((f&128)===0)return Tb(a,c),!!(b&127)}throw db();}function bc(a){return Ub(a)}function cc(a,b){if(b<0)throw Error("Tried to read a negative byte length: "+b);var c=a.cursor_,d=c+b;if(d>a.end_)throw eb(b,a.end_-c);a.cursor_=d;return c}
function dc(a,b){if(b==0)return Mb();var c=cc(a,b);a.aliasBytesFields&&a.bytesAreImmutable_?c=a.bytes_.subarray(c,c+b):(a=a.bytes_,b=c+b,c=c===b?new Uint8Array(0):Ia?a.slice(c,b):new Uint8Array(a.subarray(c,b)));return c.length==0?Mb():new Kb(c,Jb)}var ec=[],fc=void 0;function hc(){this.JSC$3866_buffer_=[]}hc.prototype.length=function(){return this.JSC$3866_buffer_.length};hc.prototype.end=function(){var a=this.JSC$3866_buffer_;this.JSC$3866_buffer_=[];return a};function ic(a,b,c){for(;c>0||b>127;)a.JSC$3866_buffer_.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.JSC$3866_buffer_.push(b)}function jc(a,b){for(;b>127;)a.JSC$3866_buffer_.push(b&127|128),b>>>=7;a.JSC$3866_buffer_.push(b)}
function kc(a,b){if(b>=0)jc(a,b);else{for(var c=0;c<9;c++)a.JSC$3866_buffer_.push(b&127|128),b>>=7;a.JSC$3866_buffer_.push(1)}}function A(a,b){a.JSC$3866_buffer_.push(b>>>0&255);a.JSC$3866_buffer_.push(b>>>8&255);a.JSC$3866_buffer_.push(b>>>16&255);a.JSC$3866_buffer_.push(b>>>24&255)};function lc(a,b,c,d){if(ec.length){var e=ec.pop();e.init(a,b,c,d);a=e}else a=new Rb(a,b,c,d);this.decoder_=a;this.fieldCursor_=this.decoder_.cursor_;this.nextWireType_=this.nextField_=-1;this.setOptions(d)}lc.prototype.setOptions=function(a){a=a===void 0?{}:a;this.discardUnknownFields=a.discardUnknownFields===void 0?!1:a.discardUnknownFields};function mc(a,b,c,d){if(nc.length){var e=nc.pop();e.setOptions(d);e.decoder_.init(a,b,c,d);return e}return new lc(a,b,c,d)}
function oc(a){a.decoder_.clear();a.nextField_=-1;a.nextWireType_=-1;nc.length<100&&nc.push(a)}function pc(a){var b=a.decoder_;if(b.cursor_==b.end_)return!1;a.fieldCursor_=a.decoder_.cursor_;var c=Vb(a.decoder_);b=c>>>3;c&=7;if(!(c>=0&&c<=5))throw cb(c,a.fieldCursor_);if(b<1)throw Error("Invalid field number: "+b+" (at position "+a.fieldCursor_+")");a.nextField_=b;a.nextWireType_=c;return!0}
function qc(a){switch(a.nextWireType_){case 0:a.nextWireType_!=0?qc(a):ac(a.decoder_);break;case 1:a=a.decoder_;Tb(a,a.cursor_+8);break;case 2:if(a.nextWireType_!=2)qc(a);else{var b=Vb(a.decoder_);a=a.decoder_;Tb(a,a.cursor_+b)}break;case 5:a=a.decoder_;Tb(a,a.cursor_+4);break;case 3:b=a.nextField_;do{if(!pc(a))throw Error("Unmatched start-group tag: stream EOF");if(a.nextWireType_==4){if(a.nextField_!=b)throw Error("Unmatched end-group tag");break}qc(a)}while(1);break;default:throw cb(a.nextWireType_,
a.fieldCursor_);}}function rc(a,b,c){var d=a.decoder_.end_,e=Vb(a.decoder_),f=a.decoder_.cursor_+e,g=f-d;g<=0&&(a.decoder_.end_=f,c(b,a,void 0,void 0,void 0),g=f-a.decoder_.cursor_);if(g)throw Error("Message parsing ended unexpectedly. Expected to read "+(e+" bytes, instead read "+(e-g)+" bytes, either the data ended unexpectedly or the message misreported its own length"));a.decoder_.cursor_=f;a.decoder_.end_=d;return b}
function sc(a){var b=Vb(a.decoder_);a=a.decoder_;var c=cc(a,b);a=a.bytes_;if(jb){var d=a,e;(e=ib)||(e=ib=new TextDecoder("utf-8",{fatal:!0}));b=c+b;d=c===0&&b===d.length?d:d.subarray(c,b);try{var f=e.decode(d)}catch(m){if(hb===void 0){try{e.decode(new Uint8Array([128]))}catch(n){}try{e.decode(new Uint8Array([97])),hb=!0}catch(n){hb=!1}}!hb&&(ib=void 0);throw m;}}else{f=c;b=f+b;c=[];for(var g=null,h,k;f<b;)h=a[f++],h<128?c.push(h):h<224?f>=b?fb():(k=a[f++],h<194||(k&192)!==128?(f--,fb()):c.push((h&
31)<<6|k&63)):h<240?f>=b-1?fb():(k=a[f++],(k&192)!==128||h===224&&k<160||h===237&&k>=160||((e=a[f++])&192)!==128?(f--,fb()):c.push((h&15)<<12|(k&63)<<6|e&63)):h<=244?f>=b-2?fb():(k=a[f++],(k&192)!==128||(h<<28)+(k-144)>>30!==0||((e=a[f++])&192)!==128||((d=a[f++])&192)!==128?(f--,fb()):(h=(h&7)<<18|(k&63)<<12|(e&63)<<6|d&63,h-=65536,c.push((h>>10&1023)+55296,(h&1023)+56320))):fb(),c.length>=8192&&(g=gb(g,c),c.length=0);f=gb(g,c)}return f}
function tc(a){var b=Vb(a.decoder_);return dc(a.decoder_,b)}function uc(a,b,c){var d=Vb(a.decoder_);for(d=a.decoder_.cursor_+d;a.decoder_.cursor_<d;)c.push(b(a.decoder_))}var nc=[];function vc(){this.blocks_=[];this.totalLength_=0;this.encoder_=new hc}function wc(a,b){b.length!==0&&(a.blocks_.push(b),a.totalLength_+=b.length)}function xc(a,b){B(a,b,2);b=a.encoder_.end();wc(a,b);b.push(a.totalLength_);return b}function yc(a,b){var c=b.pop();for(c=a.totalLength_+a.encoder_.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.totalLength_++;b.push(c);a.totalLength_++}function B(a,b,c){jc(a.encoder_,b*8+c)}function zc(a,b,c){c!=null&&(c=parseInt(c,10),B(a,b,0),kc(a.encoder_,c))}
function Ac(a,b,c){B(a,b,2);jc(a.encoder_,c.length);wc(a,a.encoder_.end());wc(a,c)}function Bc(a,b,c,d){c!=null&&(b=xc(a,b),d(c,a),yc(a,b))}function Cc(a){switch(typeof a){case "string":a.length&&a[0]==="-"?Xa(a.substring(1)):Xa(a)}};var Dc=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Ec(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Fc=Ec("jas",void 0,!0),Gc=Ec(void 0,"1oa"),Hc=Ec(void 0,Symbol()),Ic=Ec(void 0,"0ubs"),Jc=Ec(void 0,"0ubsb"),Kc=Ec(void 0,"0actk"),Lc=Ec("m_m","messagePrototypeMarker",!0);var Mc={internalArrayState:{value:0,configurable:!0,writable:!0,enumerable:!1}},Nc=Object.defineProperties,C=Dc?Fc:"internalArrayState",Oc,Pc=[];E(Pc,7);Oc=Object.freeze(Pc);function Qc(a,b){Dc||C in a||Nc(a,Mc);a[C]|=b}function E(a,b){Dc||C in a||Nc(a,Mc);a[C]=b};var Rc={};function Sc(a,b){return b===void 0?a.copyOnWrite!==Tc&&!!(2&(a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows[C]|0)):!!(2&b)&&a.copyOnWrite!==Tc}var Tc={};function Uc(a,b,c){var d=b&128?0:-1,e=a.length,f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;var g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(var h in a)!isNaN(h)&&c(+h,a[h])}}var Vc={};function Wc(a){return a&128?Vc:void 0};function Xc(a){return a};var Yc=void 0;function Zc(a,b){if(a!=null){var c;var d=(c=Yc)!=null?c:Yc={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",ob(a))}};function $c(a){return Array.prototype.slice.call(a)};var ad=typeof BigInt==="function"?BigInt.asIntN:void 0,bd=typeof BigInt==="function"?BigInt.asUintN:void 0,cd=Number.isSafeInteger,dd=Number.isFinite,ed=Math.trunc;function kd(a){if(a!=null&&typeof a!=="number")throw Error("Value of float/double field must be a number, found "+typeof a+": "+a);return a}function ld(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)}
function md(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}var nd=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function od(a){switch(typeof a){case "bigint":return!0;case "number":return dd(a);case "string":return nd.test(a);default:return!1}}function pd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return dd(a)?a|0:void 0}
function qd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return dd(a)?a>>>0:void 0}function rd(a){if(a[0]==="-")return!1;var b=a.length;return b<20?!0:b===20&&Number(a.substring(0,6))<184467}function sd(a){if(a<0){La(a);var b=Qa(x,y);a=Number(b);return cd(a)?a:b}b=String(a);if(rd(b))return b;La(a);return Pa(x,y)}
function td(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(ad(64,a));if(od(a)){if(b==="string")return b=ed(Number(a)),cd(b)?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),b=a.length,(a[0]==="-"?b<20||b===20&&Number(a.substring(0,7))>-922337:b<19||b===19&&Number(a.substring(0,6))<922337)||(Ta(a),a=x,b=y,b&2147483648?Ba()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=q(Ma(a,b)),a=b.next().value,b=b.next().value,a="-"+Qa(a,b)):a=Qa(a,b))),a;if(b==="number")return a=
ed(a),cd(a)||(La(a),a=Ra(x,y)),a}}function ud(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(bd(64,a));if(od(a)){if(b==="string")return b=ed(Number(a)),cd(b)&&b>=0?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),rd(a)||(Ta(a),a=Qa(x,y))),a;if(b==="number")return a=ed(a),a>=0&&cd(a)?a:sd(a)}}function vd(a){if(a==null||typeof a=="string"||a instanceof Kb)return a}function wd(a){if(a!=null&&typeof a!=="string")throw Error();return a}
function xd(a){return a==null||typeof a==="string"?a:void 0};function yd(a){var b=Aa(Hc);return b?a[b]:void 0}function zd(){}function Ad(a,b){for(var c in a)!isNaN(c)&&b(a,+c,a[c])}function Bd(a){var b=new zd;Ad(a,function(c,d,e){b[d]=$c(e)});b.reviveUnknownFields=a.reviveUnknownFields;return b}function Cd(a,b){b<100||Zc(Ic,1)};function Dd(a,b,c,d){var e=d!==void 0;d=!!d;var f=Aa(Hc),g;!e&&Dc&&f&&(g=a[f])&&Ad(g,Cd);f=[];var h=a.length;g=4294967295;var k=!1,m=!!(b&64),n=m?b&128?0:-1:void 0;if(!(b&1)){var w=h&&a[h-1];w!=null&&typeof w==="object"&&w.constructor===Object?(h--,g=h):w=void 0;if(m&&!(b&128)&&!e){k=!0;var v;g=((v=Ed)!=null?v:Xc)(g-n,n,a,w)+n}}b=void 0;for(v=0;v<h;v++){var z=a[v];if(z!=null&&(z=c(z,d))!=null)if(m&&v>=g){var H=v-n,D=void 0;((D=b)!=null?D:b={})[H]=z}else f[v]=z}if(w)for(var S in w)h=w[S],h!=null&&
(h=c(h,d))!=null&&(v=+S,z=void 0,m&&!Number.isNaN(v)&&(z=v+n)<g?f[z]=h:(v=void 0,((v=b)!=null?v:b={})[S]=h));b&&(k?f.push(b):f[g]=b);e&&Aa(Hc)&&(a=yd(a))&&a instanceof zd&&(f[Hc]=Bd(a));return f}
function Fd(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(Ca?a>=Ea&&a<=Ga:a[0]==="-"?Ha(a,Da):Ha(a,Fa))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[C]|0;return a.length===0&&b&1?void 0:Dd(a,b,Fd)}if(a!=null&&a[Lc]===Rc)return Gd(a);if(a instanceof Kb){b=a.JSC$3853_value_;if(b==null)a="";else if(typeof b==="string")a=b;else{if(Eb){for(var c="",d=0,e=b.length-10240;d<e;)c+=String.fromCharCode.apply(null,b.subarray(d,
d+=10240));c+=String.fromCharCode.apply(null,d?b.subarray(d):b);b=btoa(c)}else{c===void 0&&(c=0);Cb();c=yb[c];d=Array(Math.floor(b.length/3));e=c[64]||"";for(var f=0,g=0;f<b.length-2;f+=3){var h=b[f],k=b[f+1],m=b[f+2],n=c[h>>2];h=c[(h&3)<<4|k>>4];k=c[(k&15)<<2|m>>6];m=c[m&63];d[g++]=n+h+k+m}n=0;m=e;switch(b.length-f){case 2:n=b[f+1],m=c[(n&15)<<2]||e;case 1:b=b[f],d[g]=c[b>>2]+c[(b&3)<<4|n>>4]+m+e}b=d.join("")}a=a.JSC$3853_value_=b}return a}return}return a}var Ed;
function Gd(a){a=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows;return Dd(a,a[C]|0,Fd)};var Hd,Id;function Jd(a){switch(typeof a){case "boolean":return Hd||(Hd=[0,void 0,!0]);case "number":return a>0?void 0:a===0?Id||(Id=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}function Kd(a,b,c){return a=F(a,b[0],b[1],c?1:2)}
function F(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-8380417|(b&1023)<<13)}else{if(!Array.isArray(a))throw Error("narr");e=a[C]|0;2048&e&&!(2&e)&&Ld();if(e&256)throw Error("farr");if(e&64)return d!==0||e&2048||E(a,e|2048),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("pvtlmt");for(var k in h)f=+k,f<g&&(c[f+b]=h[k],delete h[k]);
e=e&-8380417|(g&1023)<<13;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-8380417|(k&1023)<<13}}}e|=64;d===0&&(e|=2048);E(a,e);return a}function Ld(){Zc(Kc,5)};function Md(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[C]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=Nd(a,c,!1,b&&!(c&16)):(Qc(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[Lc]===Rc)return b=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,c=b[C]|0,Sc(a,c)?a:Od(a,b,c)?Pd(a,b):Nd(b,c);if(a instanceof Kb)return a}function Pd(a,b,c){a=new a.constructor(b);c&&(a.copyOnWrite=Tc);a.noLegacyNull=Tc;return a}
function Nd(a,b,c,d){d!=null||(d=!!(34&b));a=Dd(a,b,Md,d);d=32;c&&(d|=2);b=b&8380609|d;E(a,b);return a}function Qd(a){if(a.copyOnWrite!==Tc)return!1;var b=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows;b=Nd(b,b[C]|0);Qc(b,2048);a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=b;a.copyOnWrite=void 0;a.noLegacyNull=void 0;return!0}function Rd(a){if(!Qd(a)&&Sc(a,a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows[C]|0))throw Error();}
function Sd(a,b){b===void 0&&(b=a[C]|0);b&32&&!(b&4096)&&E(a,b|4096)}function Od(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.copyOnWrite=Tc,!0):!1};function Td(a,b,c){a=Ud(a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,b,void 0,c);if(a!==null)return a}function Ud(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}}
function Vd(a,b,c){Rd(a);var d=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows;G(d,d[C]|0,b,c);return a}function G(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[C]|0)>>13&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b}function Wd(a,b){return Xd(a,a[C]|0,b)}
function Yd(a){return a==null?a:typeof a==="string"?a?new Kb(a,Jb):Mb():a.constructor===Kb?a:Db&&a!=null&&a instanceof Uint8Array?a.length?new Kb(new Uint8Array(a),Jb):Mb():void 0}function Xd(a,b,c){if(b&2)throw Error();var d=Wc(b);var e=Ud(a,c,d);e=Array.isArray(e)?e:Oc;var f=e===Oc?7:e[C]|0;var g=f;2&b&&(g|=2);g|=1;if(2&g||2&g&&4&g||256&g||16&g)e=$c(e),f=0,g=Zd(g,b),G(a,b,c,e,d);g&=-13;g!==f&&E(e,g);return e}
function $d(a,b,c,d){Rd(a);a=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows;var e=a[C]|0;if(d==null){var f=ae(a);if(be(f,a,e,c)===b)f.set(c,0);else return}else e=ce(a,e,c,b);G(a,e,b,d)}function de(a,b,c,d){var e=a[C]|0,f=Wc(e);e=ce(a,e,c,b,f);G(a,e,b,d,f)}function ae(a){if(Dc){var b;return(b=a[Gc])!=null?b:a[Gc]=new Map}if(Gc in a)return a[Gc];b=new Map;Object.defineProperty(a,Gc,{value:b});return b}
function ce(a,b,c,d,e){var f=ae(a),g=be(f,a,b,c,e);g!==d&&(g&&(b=G(a,b,g,void 0,e)),f.set(c,d));return b}function be(a,b,c,d,e){var f=a.get(d);if(f!=null)return f;for(var g=f=0;g<d.length;g++){var h=d[g];Ud(b,h,e)!=null&&(f!==0&&(c=G(b,c,f,void 0,e)),f=h)}a.set(d,f);return f}
function ee(a,b,c){var d=a[C]|0,e=Wc(d),f=Ud(a,c,e);if(f!=null&&f[Lc]===Rc){if(!Sc(f))return Qd(f),f.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows;var g=f.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows}else Array.isArray(f)&&(g=f);if(g){var h=g[C]|0;h&2&&(g=Nd(g,h))}g=Kd(g,b,!0);g!==f&&G(a,d,c,g,e);return g}
function fe(a,b){var c=ge,d=!1,e=Ud(a,4,void 0,function(f){if(f!=null&&f[Lc]===Rc)var g=f;else if(Array.isArray(f)){g=f[C]|0;var h=g|b&32;h|=b&2;h!==g&&E(f,h);g=new c(f)}else g=void 0;d=g!==f&&g!=null;return g});if(e!=null)return d&&!Sc(e)&&Sd(a,b),e}
function he(a){var b=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,c=b[C]|0,d=fe(b,c);if(d==null)return d;c=b[C]|0;if(!Sc(a,c)){var e=d;var f=e.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,g=f[C]|0;e=Sc(e,g)?Od(e,f,g)?Pd(e,f,!0):new e.constructor(Nd(f,g,!1)):e;e!==d&&(Qd(a)&&(b=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,c=b[C]|0),d=e,c=G(b,c,4,d),Sd(b,c))}return d}function ie(a){a==null&&(a=void 0);return a}
function je(a,b,c){c=ie(c);Vd(a,b,c);c&&!Sc(c)&&Sd(a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows);return a}
function ke(a,b){Rd(a);var c=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,d=c[C]|0;if(b==null)return G(c,d,1),a;for(var e=b===Oc?7:b[C]|0,f=e,g=!!(2&e)&&!!(4&e)||!!(256&e),h=g||Object.isFrozen(b),k=!0,m=!0,n=0;n<b.length;n++){var w=b[n];g||(w=Sc(w),k&&(k=!w),m&&(m=w))}g||(e=k?13:5,e=m?e&-4097:e|4096);h&&e===f||(b=$c(b),f=0,e=Zd(e,d));e!==f&&E(b,e);d=G(c,d,1,b);2&e||!(4096&e||16&e)||Sd(c,d);return a}function Zd(a,b){return a=(2&b?a|2:a&-3)&-273};function I(a,b,c){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a,b,c)}I.prototype.toJSON=function(){var a=Gd(this);return a};I.prototype[Lc]=Rc;I.prototype.toString=function(){return this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows.toString()};function J(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var le=J(),me=J(),ne=J(),oe=J(),pe=J(),qe=J(),re=J(),se=J(),te=J(),ue=J();function ve(a,b,c){this.$$binaryReaderFn=a;this.$$binaryWriterFn=b;a=Aa(le);this.$$isMsg=!!a&&c===a||!1}function we(a,b){var c=c===void 0?le:c;return new ve(a,b,c)}function xe(a,b,c,d,e){Bc(a,c,ye(b,d),e)}var ze=we(function(a,b,c,d,e){if(a.nextWireType_!==2)return!1;rc(a,ee(b,d,c),e);return!0},xe),Ae=we(function(a,b,c,d,e){if(a.nextWireType_!==2)return!1;rc(a,ee(b,d,c),e);return!0},xe),Be=Symbol(),Ce=Symbol(),De=Symbol(),Ee=Symbol(),Fe=Symbol(),Ge,He;
function Ie(a,b,c,d){var e=d[a];if(e)return e;e={};e.binaryFields=d;e.messageMetadata=Jd(d[0]);var f=d[1],g=1;f&&f.constructor===Object&&(e.extensions=f,f=d[++g],typeof f==="function"&&(e.isMessageSet=!0,Ge!=null||(Ge=f),He!=null||(He=d[g+1]),f=d[g+=2]));for(var h={};f&&Array.isArray(f)&&f.length&&typeof f[0]==="number"&&f[0]>0;){for(var k=0;k<f.length;k++)h[f[k]]=f;f=d[++g]}for(k=1;f!==void 0;){typeof f==="number"&&(k+=f,f=d[++g]);var m=void 0;if(f instanceof ve)var n=f;else n=ze,g--;f=void 0;if((f=
n)==null?0:f.$$isMsg){f=d[++g];m=d;var w=g;typeof f==="function"&&(f=f(),m[w]=f);m=f}f=d[++g];w=k+1;typeof f==="number"&&f<0&&(w-=f,f=d[++g]);for(;k<w;k++){var v=h[k];m?c(e,k,n,m,v):b(e,k,n,v)}}return d[a]=e}function Je(a){return Array.isArray(a)?a[0]instanceof ve?a:[Ae,a]:[a,void 0]}function ye(a,b){if(a instanceof I)return a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows;if(Array.isArray(a))return Kd(a,b,!1)};function Ke(a,b,c,d){var e=c.$$binaryReaderFn;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function Le(a,b,c,d,e){var f=c.$$binaryReaderFn,g,h;a[b]=function(k,m,n){return f(k,m,n,h||(h=Ie(Ce,Ke,Le,d).messageMetadata),g||(g=Me(d)),e)}}
function Me(a){var b=a[De];if(b!=null)return b;var c=Ie(Ce,Ke,Le,a);b=c.isMessageSet?function(d,e){return Ge(d,e,c)}:function(d,e){for(;pc(e)&&e.nextWireType_!=4;){var f=e.nextField_,g=c[f];if(g==null){var h=c.extensions;h&&(h=h[f])&&(h=Ne(h),h!=null&&(g=c[f]=h))}if(g==null||!g(e,d,f)){h=e;g=h.fieldCursor_;qc(h);if(h.discardUnknownFields)var k=void 0;else{var m=h.decoder_.cursor_-g;h.decoder_.cursor_=g;k=dc(h.decoder_,m)}m=h=g=void 0;var n=d;k&&((g=(h=(m=n[Hc])!=null?m:n[Hc]=new zd)[f])!=null?g:h[f]=
[]).push(k)}}if(d=yd(d))d.reviveUnknownFields=c.binaryFields[Fe];return!0};a[De]=b;a[Fe]=Oe.bind(a);return b}
function Oe(a,b,c,d){var e=this[Ce],f=this[De],g=Kd(void 0,e.messageMetadata,!1),h=yd(a);if(h){var k=!1,m=e.extensions;if(m){e=function(H,D,S){if(S.length!==0)if(m[D])for(H=q(S),D=H.next();!D.done;D=H.next()){D=mc(D.value);try{k=!0,f(g,D)}finally{oc(D)}}else d==null||d(a,D,S)};if(b==null)Ad(h,e);else if(h!=null){var n=h[b];n&&e(h,b,n)}if(k){var w=a[C]|0;if(w&2&&w&2048&&(c==null||!c.reviveIntoImmutable))throw Error();var v=Wc(w),z=function(H,D){if(Ud(a,H,v)!=null)switch(c==null?void 0:c.resolutionBehavior){case 1:return;
default:throw Error();}D!=null&&(w=G(a,w,H,D,v));delete h[H]};b==null?Uc(g,g[C]|0,function(H,D){z(H,D)}):z(b,Ud(g,b,v))}}}}function Ne(a){a=Je(a);var b=a[0].$$binaryReaderFn;if(a=a[1]){var c=Me(a),d=Ie(Ce,Ke,Le,a).messageMetadata;return function(e,f,g){return b(e,f,g,d,c)}}return b};function Pe(a,b,c){a[b]=c.$$binaryWriterFn}function Qe(a,b,c,d){var e,f,g=c.$$binaryWriterFn;a[b]=function(h,k,m){return g(h,k,m,f||(f=Ie(Be,Pe,Qe,d).messageMetadata),e||(e=Re(d)))}}function Re(a){var b=a[Ee];if(!b){var c=Ie(Be,Pe,Qe,a);b=function(d,e){return Se(d,e,c)};a[Ee]=b}return b}
function Se(a,b,c){Uc(a,a[C]|0,function(d,e){if(e!=null){var f=Te(c,d);f?f(b,e,d):d<500||Zc(Jc,3)}});(a=yd(a))&&Ad(a,function(d,e,f){wc(b,b.encoder_.end());for(d=0;d<f.length;d++)wc(b,Ob(f[d])||new Uint8Array(0))})}function Te(a,b){var c=a[b];if(c)return c;if(c=a.extensions)if(c=c[b]){c=Je(c);var d=c[0].$$binaryWriterFn;if(c=c[1]){var e=Re(c),f=Ie(Be,Pe,Qe,c).messageMetadata;c=a.isMessageSet?He(f,e):function(g,h,k){return d(g,h,k,f,e)}}else c=d;return a[b]=c}};function K(a,b,c){if(Array.isArray(b)){var d=b[C]|0;if(d&4)return b;for(var e=0,f=0;e<b.length;e++){var g=a(b[e]);g!=null&&(b[f++]=g)}f<e&&(b.length=f);c&&(E(b,(d|5)&-1537),d&2&&Object.freeze(b));return b}}function L(a,b,c){return new ve(a,b,c)}function M(a,b,c){return new ve(a,b,c)}function N(a,b,c){G(a,a[C]|0,b,c,Wc(a[C]|0))}
var Ue=we(function(a,b,c,d,e){if(a.nextWireType_!==2)return!1;a=rc(a,Kd([void 0,void 0],d,!0),e);d=b[C]|0;e=Wc(d);if(d&2)throw Error();var f=Ud(b,c,e);if(Array.isArray(f)){if((f[C]|0)&2){f=$c(f);for(var g=0;g<f.length;g++){var h=f[g]=$c(f[g]);if(Array.isArray(h[1])){var k=h[1];Qc(k,34);h[1]=k}}G(b,d,c,f,e)}f.push(a)}else G(b,d,c,[a],e);return!0},function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++){var g=b[f];Array.isArray(g)&&Bc(a,c,Kd(g,d,!1),e)}});
function Ve(a,b,c){b=ld(b);b!=null&&(B(a,c,1),a=a.encoder_,Oa(b),A(a,x),A(a,y))}function We(a,b,c){b=ld(b);b!=null&&(B(a,c,5),a=a.encoder_,Na(b),A(a,x))}function Xe(a,b,c){b=td(b);if(b!=null){switch(typeof b){case "string":ab(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.encoder_;La(b);ic(a,x,y);break;case "bigint":c=$a(b);ic(a.encoder_,c.JSC$3838_lo,c.JSC$3838_hi);break;default:c=ab(b),ic(a.encoder_,c.JSC$3838_lo,c.JSC$3838_hi)}}}
function Ye(a,b,c){b=ud(b);if(b!=null){switch(typeof b){case "string":Xa(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.encoder_;La(b);ic(a,x,y);break;case "bigint":c=Wa(b);ic(a.encoder_,c.JSC$3835_lo,c.JSC$3835_hi);break;default:c=Xa(b),ic(a.encoder_,c.JSC$3835_lo,c.JSC$3835_hi)}}}function Ze(a,b,c){b=pd(b);b!=null&&b!=null&&(B(a,c,0),kc(a.encoder_,b))}function $e(a,b,c){b=md(b);b!=null&&(B(a,c,0),a.encoder_.JSC$3866_buffer_.push(b?1:0))}
function af(a,b,c){b=xd(b);b!=null&&Ac(a,c,nb(b))}function bf(a,b,c,d,e){Bc(a,c,ye(b,d),e)}function cf(a,b,c){zc(a,c,pd(b))}function df(a,b,c){if(a.nextWireType_!==5&&a.nextWireType_!==2)return!1;b=Wd(b,c);a.nextWireType_==2?uc(a,Zb,b):b.push(Zb(a.decoder_));return!0}function ef(a,b,c){if(a.nextWireType_!==0&&a.nextWireType_!==2)return!1;b=Wd(b,c);a.nextWireType_==2?uc(a,Ub,b):b.push(Ub(a.decoder_));return!0}
function ff(a,b,c){if(a.nextWireType_!==0&&a.nextWireType_!==2)return!1;b=Wd(b,c);a.nextWireType_==2?uc(a,ac,b):b.push(ac(a.decoder_));return!0}
var gf=L(function(a,b,c,d){if(a.nextWireType_!==1)return!1;de(b,c,d,$b(a.decoder_));return!0},Ve,se),O=L(function(a,b,c){if(a.nextWireType_!==5)return!1;N(b,c,Zb(a.decoder_));return!0},We,re),hf=M(df,function(a,b,c){b=K(ld,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,5),e=e.encoder_,Na(g),A(e,x))}},re),jf=M(df,function(a,b,c){b=K(ld,b,!0);if(b!=null&&b.length)for(B(a,c,2),jc(a.encoder_,b.length*4),c=0;c<b.length;c++){var d=a.encoder_;Na(b[c]);A(d,x)}},re),kf=L(function(a,
b,c,d){if(a.nextWireType_!==5)return!1;de(b,c,d,Zb(a.decoder_));return!0},We,re),lf=L(function(a,b,c){if(a.nextWireType_!==0)return!1;N(b,c,Xb(a.decoder_));return!0},Xe,pe),mf=M(function(a,b,c){if(a.nextWireType_!==0&&a.nextWireType_!==2)return!1;b=Wd(b,c);a.nextWireType_==2?uc(a,Xb,b):b.push(Xb(a.decoder_));return!0},function(a,b,c){b=K(td,b,!1);if(b!=null&&b.length){c=xc(a,c);for(var d=0;d<b.length;d++){var e=b[d];switch(typeof e){case "number":var f=a.encoder_;La(e);ic(f,x,y);break;case "bigint":e=
$a(e);ic(a.encoder_,e.JSC$3838_lo,e.JSC$3838_hi);break;default:e=ab(e),ic(a.encoder_,e.JSC$3838_lo,e.JSC$3838_hi)}}yc(a,c)}},pe),nf=L(function(a,b,c,d){if(a.nextWireType_!==0)return!1;de(b,c,d,Xb(a.decoder_));return!0},Xe,pe),of=L(function(a,b,c){if(a.nextWireType_!==0)return!1;N(b,c,Sb(a.decoder_,Qa));return!0},Ye,qe),pf=L(function(a,b,c){if(a.nextWireType_!==0)return!1;N(b,c,Sb(a.decoder_,Pa));return!0},Ye,qe),P=L(function(a,b,c){if(a.nextWireType_!==0)return!1;N(b,c,Ub(a.decoder_));return!0},Ze,
oe),qf=M(ef,function(a,b,c){b=K(pd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),kc(e.encoder_,g))}},oe),rf=M(ef,function(a,b,c){b=K(pd,b,!0);if(b!=null&&b.length){c=xc(a,c);for(var d=0;d<b.length;d++)kc(a.encoder_,b[d]);yc(a,c)}},oe),sf=L(function(a,b,c,d){if(a.nextWireType_!==0)return!1;de(b,c,d,Ub(a.decoder_));return!0},Ze,oe),Q=L(function(a,b,c){if(a.nextWireType_!==0)return!1;N(b,c,ac(a.decoder_));return!0},$e,me),tf=M(ff,function(a,b,c){b=K(md,b,!0);if(b!=
null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),e.encoder_.JSC$3866_buffer_.push(g?1:0))}},me),uf=M(ff,function(a,b,c){b=K(md,b,!0);if(b!=null&&b.length)for(B(a,c,2),jc(a.encoder_,b.length),c=0;c<b.length;c++)a.encoder_.JSC$3866_buffer_.push(b[c]?1:0)},me),vf=L(function(a,b,c,d){if(a.nextWireType_!==0)return!1;de(b,c,d,ac(a.decoder_));return!0},$e,me),wf=L(function(a,b,c,d){if(a.nextWireType_!==2)return!1;de(b,c,d,sc(a));return!0},af,ne),R=L(function(a,b,c){if(a.nextWireType_!==
2)return!1;N(b,c,sc(a));return!0},af,ne),T=M(function(a,b,c){if(a.nextWireType_!==2)return!1;a=sc(a);Xd(b,b[C]|0,c).push(a);return!0},function(a,b,c){b=K(xd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Ac(e,f,nb(g))}},ne),U,xf=void 0;xf=xf===void 0?le:xf;U=new ve(function(a,b,c,d,e){if(a.nextWireType_!==2)return!1;d=Kd(void 0,d,!0);Xd(b,b[C]|0,c).push(d);rc(a,d,e);return!0},function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)bf(a,b[f],c,d,e)},xf);
var V=we(function(a,b,c,d,e,f){if(a.nextWireType_!==2)return!1;var g=b[C]|0;ce(b,g,f,c,Wc(g));b=ee(b,d,c);rc(a,b,e);return!0},bf),yf=L(function(a,b,c){if(a.nextWireType_!==2)return!1;N(b,c,tc(a));return!0},function(a,b,c){b=vd(b);b!=null&&Ac(a,c,Qb(b,!0).buffer)},te),W=L(function(a,b,c){if(a.nextWireType_!==0)return!1;N(b,c,Vb(a.decoder_));return!0},function(a,b,c){b=qd(b);b!=null&&b!=null&&(B(a,c,0),jc(a.encoder_,b))},J()),X=L(function(a,b,c){if(a.nextWireType_!==0)return!1;N(b,c,Ub(a.decoder_));
return!0},cf,ue),zf=M(function(a,b,c){if(a.nextWireType_!==0&&a.nextWireType_!==2)return!1;b=Wd(b,c);a.nextWireType_==2?uc(a,bc,b):b.push(Ub(a.decoder_));return!0},function(a,b,c){b=K(pd,b,!0);if(b!=null)for(var d=0;d<b.length;d++)zc(a,c,b[d])},ue),Y=L(function(a,b,c,d){if(a.nextWireType_!==0)return!1;de(b,c,d,Ub(a.decoder_));return!0},cf,ue),Af=M(function(a,b,c){if(a.nextWireType_!==0&&a.nextWireType_!==2)return!1;b=Wd(b,c);a.nextWireType_==2?uc(a,Wb,b):b.push(Wb(a.decoder_));return!0},function(a,
b,c){b=K(pd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),jc(e.encoder_,(g<<1^g>>31)>>>0))}},J()),Bf=[!0,R,P],Cf=[!0,R,Q],Df=[!0,R,R];function Ef(a){return function(b){var c=new vc;Se(b.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,c,Ie(Be,Pe,Qe,a));wc(c,c.encoder_.end());b=new Uint8Array(c.totalLength_);for(var d=c.blocks_,e=d.length,f=0,g=0;g<e;g++){var h=d[g];b.set(h,f);f+=h.length}c.blocks_=[b];return b}};var Ff=[0,L(function(a,b,c){if(a.nextWireType_!==1)return!1;var d=a.decoder_;a=Yb(d);d=Yb(d);N(b,c,Qa(a,d));return!0},function(a,b,c){b=ud(b);if(b!=null)switch(Cc(b),B(a,c,1),a=a.encoder_,Cc(b),typeof b){case "number":b<0?(c=-b,c=Va(new Ua(c&4294967295,c/4294967296)),b=c.JSC$3835_hi,A(a,c.JSC$3835_lo),A(a,b)):(Ka(b),A(a,x),A(a,y));break;case "bigint":c=b<BigInt(0)?Va(Wa(-b)):Wa(b);b=c.JSC$3835_hi;A(a,c.JSC$3835_lo);A(a,b);break;default:c=b.length&&b[0]==="-"?Va(Xa(b.substring(1))):Xa(b),b=c.JSC$3835_hi,
A(a,c.JSC$3835_lo),A(a,b)}},J()),-1];var Gf=[0,L(function(a,b,c){if(a.nextWireType_!==5)return!1;a=a.decoder_;var d=a.bytes_,e=a.cursor_,f=d[e],g=d[e+1],h=d[e+2];d=d[e+3];Tb(a,a.cursor_+4);N(b,c,f<<0|g<<8|h<<16|d<<24);return!0},function(a,b,c){b=pd(b);b!=null&&(B(a,c,5),a=a.encoder_,a.JSC$3866_buffer_.push(b>>>0&255),a.JSC$3866_buffer_.push(b>>>8&255),a.JSC$3866_buffer_.push(b>>>16&255),a.JSC$3866_buffer_.push(b>>>24&255))},J()),-1];var Hf=[0,X,-1,lf,R,Gf,-1,O,P,X,Ff,R,X,-1,[0,Gf,-1],P,pf,Ff,O,[0,1,P,-4,L(function(a,b,c){if(a.nextWireType_!==1)return!1;N(b,c,$b(a.decoder_));return!0},Ve,se),[0,O,-1,P],R,O,U,[0,X,P],P,-1,X,-2,O,-1,X,O,X,P,[0,3,P,-1,1,W,-1,P,M(function(a,b,c){if(a.nextWireType_!==2)return!1;a=tc(a);Xd(b,b[C]|0,c).push(a);return!0},function(a,b,c){b=K(vd,b,!1);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Ac(e,f,Qb(g,!0).buffer)}},te)]],R,zf,U,[0,Ff,U,[0,R,X],O,X,-1],1,U,[0,pf,-1,W],X,Ff];var If=[0,lf,[0,O,R,P,R,P,qf,lf,R,P,R,-1,O,P,O],yf,[0,M(function(a,b,c){if(a.nextWireType_!==1&&a.nextWireType_!==2)return!1;b=Wd(b,c);if(a.nextWireType_==2){c=a.decoder_;a=Vb(a.decoder_)/8;var d=c.cursor_,e=8*a;if(d+e>c.end_)throw eb(e,c.end_-d);var f=c.bytes_;d+=f.byteOffset;fc===void 0&&(fc=(new Uint16Array((new Uint8Array([1,2])).buffer))[0]==513);if(fc)for(c.cursor_+=e,c=new Float64Array(f.buffer.slice(d,d+e)),a=0;a<c.length;a++)b.push(c[a]);else for(e=0;e<a;e++)b.push($b(c))}else b.push($b(a.decoder_));
return!0},function(a,b,c){b=K(ld,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,1),e=e.encoder_,Oa(g),A(e,x),A(e,y))}},se),-1]];function ge(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a)}p(ge,I);function Jf(a){a=Td(a,1,Yd);return a==null?Mb():a}function Kf(a){var b=16E3;b=b===void 0?0:b;a=pd(Td(a,2));return a!=null?a:b};function Lf(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a)}p(Lf,I);function Mf(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a)}p(Mf,I);var Nf=[0,yf,P];var Of=[0,[1,2,3,4],wf,Y,V,[0,R,X],Y];var Pf=[0,R,-5,O,R,T,X,-1,U,Of,R,-2];var Qf=[0,P,-3];var Sf=[0,[1,2,3,4],vf,-1,wf,-1];var Uf=[0,R,-1,1,R,-1,6,T,[0,W,R,W,P,W,-4,O,W,O,-1],Q,T,-1];var Z=[0,X,-5];var Vf=[0,[0,R,-5,Q,T,Z],R,-7,Q,R,T,Z];var Wf=[0,T,1,X,-1,R];var Xf=[0,R,-2,Z,R];var Yf=[0,R,-1,Q,R,T,Z];var Zf=[0,U,[0,R,-1],R,Q,R];var $f=[0,R,-2,Z];var ag=[0,R,-3,P,R,Q,R,-1,Q,R,T,Z,R,-2];var bg=[0,Q,R,-3,P,R,Q,R,T,Z];var cg=[0,R,-3,P,R,-3,Q,R,T,Z];var dg=[0,R,P,X,R];var eg=[0,R,-2,P,R,Q,R,Q,T,Z];var fg=[0,R,-2,Q];var gg=[0,bg,eg,Yf,R,P,R,Q,R,T,Z];var hg=[0,bg,lf,R,P,R,Q,R,T,Z,R];var ig=[0,R,-1,Q,R,T,Z,Q];var jg=[0,R,P,Q];var kg=[0,R,T,R,P,R,Q,R,T,Z];var lg=[0,P,-2,Q,R,P,R,P,R,Q,R,T,Z,Q];var mg=[0,X,-1];var ng=[0,O,-1];var og=[0,U,[0,O,-2],O,-1,P,U,[0,P,X,P,X,W,X,-1,U,ng,[0,O,-1],[0,U,ng,O,X],[0,U,ng,X]],O];var pg=[0,O,-2];var qg=[-11,{},Qf,R,[0,uf,rf,jf,T,U,[0,jf],[0,jf]],jf,R,-1,[0,pg],R,[0,jf,-1,U,[0,X,P]],-1];var rg=[0,Qf,[0,Q,O,jf,-1],P,[0,jf]];var sg=[0,X,[0,qf,mf]];var tg=[0,X,[0,qf,T]];var ug=[0,P,-1,X,P];var vg=[0,jf,rf];var wg=[0,[0,of,X,Q]];var xg=[0,P,-2,R];var yg=[0,X];var Ag=[-15,{},U,[-44,{},[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,21,25,32,36,37,41],wf,R,V,Yf,V,ig,V,bg,V,eg,V,lg,V,gg,V,ag,V,Vf,V,kg,V,hg,V,cg,V,Zf,wf,-1,U,fg,wf,-1,og,kf,[0,Q,-1,X,mg,Q,-1,O,Q,T,ug,X,-1],Hf,Q,V,[0,R,-1],U,[0,R,-1],[0,T,Q],Z,X,yg,Q,V,jg,R,T,R,V,$f,V,Xf,R,-1,Q,V,dg,Q,xg],U,[0,R,U,[0,R,-1,X],U,[0,R,-1],R,X,[0,X,-3],T,Q,R],4,yg,O,Q,function(){return zg},R,wg,Q,[0,Q,-1]],zg=[0,U,function(){return Ag},-1];var Bg=function(a,b){return function(c,d){var e={treatNewDataAsImmutable:!0};d&&Object.assign(e,d);c=mc(c,void 0,void 0,e);try{var f=new a,g=f.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows;Me(b)(g,c);var h=f}finally{oc(c)}return h}}(Mf,[0,X,2,Nf,X,[-500,{},pf,R,Ag,-1,1,[0,X,P,-1,O],[0,R,-5,P,R,1,Q,-1,R,X,U,Pf,R],lf,-2,89,[-5,{},U,[-75,{},Qf,W,-1,R,X,R,-2,Q,O,X,R,Q,-1,5,Yf,ig,R,bg,eg,lg,gg,bg,ag,Vf,kg,hg,cg,R,-1,$f,R,Xf,1,Zf,dg,[0,R,-1],U,fg,7,Uf,1,R,Q,R,Q,jg,R,Q,R,-2,Sf,R,Q,O,T,1,R,Q,1,R,
Wf,X,Q],U,[-71,{},Qf,X,R,-1,Q,1,R,X,Uf,O,X,Q,zf,R,mg,1,P,Q,1,R,X,O,[0,[0,O,-2],[0,O,-2]],[0,X,-2],25,og,R,3,Q,-1,1,Q,R,2,Q,Sf,R,X,O,R,-1,1,R],U,[-11,{},Qf,R,X,5,[0,P,-3],R],U,[-12,{},Qf,R,Q,O,-1,[0,O,-6,U,[0,R,X,O]],hf,P,-1,R,[0,[0,P,-3],U,[0,R,O]]]],1,[0,3,U,[0,U,[0,P,-2]],Q],3,ug,X,-1,1,[-8,{},ug,X,-1,[0,X,2,X,-1],X,-1,R],39,[0,[0,P,-2,rf,-2],tg,-2,sg,tg,-2,sg,-5],49,[-3,{},[0,U,qg,[0,U,[0,R,U,[0,P,O,U,[0,P,O,-1,P],Q],U,[0,P,O],Q,-2]]],U,[0,P,U,[0,Qf,[-10,{},P,-2,W,[0,W,-2,O,-8,hf,-5,Af,-1],zf,
P,-2],pg,O,-2,U,[0,X,hf]]]],[-3,{},[0,U,qg],U,[-6,{},U,rg,U,pg,qf,tf,rf]],48,[0,[0,U,rg,If],[0,O,W,-1,O,W]],49,Nf,599,[-1,{}],Q,[0,O,-2,P],[-3,{},U,[-7,{},W,-1,Q,U,[0,[1,2,3,4],V,[-5,{},X,R,-1,Q],V,[0],V,[0],V,[0]],O,W],W],vg]]);var Cg=Ef(Pf);function Dg(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a)}p(Dg,I);var Eg=[1,4];function Fg(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a,10)}p(Fg,I);var Gg=[0,P,yf,X];var Hg=[-10,{},[0,U,[0,X,1,X],zf,Hf,T,U,[0,R,X,O,X],1,X,-1,Q],[0,R,-3,O,[0,P,R],zf,-1],[0,Eg,kf,[0,X],[0,2,X],Y,[0,Q,-1],O,X,-2],[0,1,O,U,[0,R,-1],zf,wg,P],Wf,[-1,{}],[0,[1,3],V,[0,[3,4],U,Of,-1,sf,vf,U,Of],R,wf],[0,[1,2,3,4,5,6,7,8,9,10,11],Y,-10],[0,[1,2],[3,4,5],V,Gg,V,vg,V,Gg,V,vg,V,[0,jf]]];var Ig=[-3,{},R,Hg];function Jg(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a)}p(Jg,I);function Kg(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a,5)}p(Kg,I);function Lg(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a)}p(Lg,I);var Mg=[2,3,4];var Ng=[0,R,-2];var Og=[0,[3,4],R,-1,nf,gf,P,-1,R,-1];var Pg=[0,Mg,P,V,[-5,{},U,[0,[100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],P,R,-1,Hg,U,[0,[4,5],P,R,-1,Y,wf,R,Hg,X],R,-1,xg,Q,90,wf,V,[0,R,X,[0,X,O,X]],V,[0,R],V,[0,R,P],V,[0,R,X],V,[0,R,-1],V,[0,R,X],V,Og,V,[0,1,R],V,Ng,V,[0,T,X],V,[0,[5,6,7],P,-2,R,Y,-1,sf],V,[0,[5,6],P,-3,Y,sf],V,[0,[1,2],[4,5,6],V,Og,V,Ng,R,Y,-1,sf],V,[0,[3,4],[8,9,10],P,-1,sf,wf,P,X,R,Y,-1,sf],V,[0,R,T,R],V,[0,[4,5,6],Og,R,1,Y,-1,sf],V,[0,R,-3,P,R,-2],V,[0,R,X],V,[0,U,[0,R,-1],R,Q],V,[0,
R,-1]],Hg,U,[0,P,-1,Hg],Q],V,Ig,V,[0,[1,2],V,Gg,V,[0,R]]];var Qg=[0,Ue,Cf,Ue,Bf,Ue,Df];function Rg(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a,4)}p(Rg,I);var Sg=[-4,{},U,Pg,Hg,Qg];function Tg(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=F(a,3)}p(Tg,I);var Ug=Ef([-3,{},U,Ag,Sg]);function Vg(a){a=a===void 0?new AudioContext({sampleRate:24E3}):a;this.initCalled=!1;this.voiceData=[];this.voiceNameToUrl={};this.voiceNameToId={};this.voiceNameToFileId={};this.voiceNameToSpeakerName={};this.voiceNameToDependentVoiceId={};this.textEncoder=new TextEncoder;this.currentVoice="";this.lastPartialBuffer=null;this.lastPartialBufferLength=0;this.sampleBuffers=[];this.isReadingMoreSamples=this.pausedByClient=this.playbackStarted=this.audioPlaying=!1;this.timepointEventQueue=[];this.scheduledTimepointEvents=
[];this.scheduledReadingEvents=[];this.JSC$3934_context=a;this.gainNode=this.JSC$3934_context.createGain()}aa=Vg.prototype;aa.init=function(a){var b=this;return t(function(c){switch(c.nextAddress){case 1:if(b.initCalled)return c.return();b.initCalled=!0;b.extensionId=a;return r(c,loadWasmTtsBindings(),2);case 2:return b.mainModule=c.yieldResult,r(c,Wg(b),3);case 3:return r(c,Xg(b),4);case 4:return c.return(Yg(b))}})};
aa.onLanguageStatusRequest=function(a){var b=this,c;return t(function(d){return d.nextAddress==1?r(d,b.init(b.extensionId),2):d.nextAddress!=3?(c=a,r(d,Zg(b,a),3)):d.return({type:"offscreenLanguageStatusResponse",lang:c,status:d.yieldResult})})};aa.onInstallLanguageRequest=function(a){var b=this,c;return t(function(d){return d.nextAddress==1?r(d,b.init(b.extensionId),2):d.nextAddress!=3?(c=a,r(d,$g(b,a),3)):d.return({type:"offscreenLanguageStatusResponse",lang:c,status:d.yieldResult})})};
aa.onUninstallLanguageRequest=function(a){var b=this,c,d,e,f,g,h;return t(function(k){if(k.nextAddress==1)return r(k,b.init(b.extensionId),2);c=ah(b,a);d=!1;e=q(c);for(f=e.next();!f.done;f=e.next())if(g=f.value,bh(b,g),g.remote&&!g.unloaded){h="/voices/"+g.file_id;try{if(b.mainModule)try{for(var m=b.mainModule.FS.readdir(h),n=q(m),w=n.next();!w.done;w=n.next()){var v=w.value;v!=="."&&v!==".."&&b.mainModule.FS.unlink(h+"/"+v)}b.mainModule.FS.rmdir(h)}catch(z){}d=!0}catch(z){}}d&&ch(b);return k.return({type:"offscreenLanguageStatusResponse",
lang:a,status:"notInstalled"})})};aa.onStop=function(a){var b=this;return t(function(c){if(!b.initCalled)return c.return();dh(b);b.audioPlaying=!1;b.playbackStarted=!1;b.pausedByClient=a;b.streamingNode&&(b.streamingNode.disconnect(),b.streamingNode.port.postMessage({command:"clearBuffers"}));for(eh(b);b.scheduledTimepointEvents.length>0;)window.clearTimeout(b.scheduledTimepointEvents.pop());b.timepointEventQueue=[];b.sampleBuffers.length=0;c.nextAddress=0})};
aa.onPause=function(){var a=this;return t(function(b){if(b.nextAddress==1)return a.initCalled?r(b,a.JSC$3934_context.suspend(),2):b.return();eh(a);a.pausedByClient=!0;a.audioPlaying=!1;b.nextAddress=0})};aa.onResume=function(){var a=this;return t(function(b){if(!a.initCalled||a.audioPlaying)return b.return();a.pausedByClient=!1;if(!a.playbackStarted)return eh(a),fh(a),b.return();a.audioPlaying=!0;gh(a);return b.return(a.JSC$3934_context.resume())})};
aa.onSpeak=function(a,b){var c=this,d,e,f,g,h;return t(function(k){switch(k.nextAddress){case 1:return c.pausedByClient=!1,r(k,c.init(c.extensionId),2);case 2:if(!c.mainModule)throw Error("WASM module not initialized.");return b.voiceName?r(k,c.onStop(!1),3):k.return();case 3:c.utterance=a;d=b.voiceName;if(c.currentVoice===d){k.nextAddress=4;break}k.catchAddress_=5;return r(k,hh(c,d,!1),7);case 7:e=c.voiceNameToFileId[d];if(!e)throw Error("Invalid voice name: "+b.voiceName);f=["/voices",e].join("/");
g=[f,"pipeline.pb"].join("/");if(c.mainModule){var m=ih(c,g);var n=ih(c,f),w=c.mainModule._GoogleTtsInit(m,n);c.mainModule._free(n);c.mainModule._free(m);m=w===1}else m=!1;if(!m)throw Error("Failed to initialize pipeline "+g);k.nextAddress=4;k.catchAddress_=0;break;case 5:return qa(k),k.return(Promise.reject(Error("Voice is not available")));case 4:c.currentVoice=d;try{if(m=d,c.mainModule&&a.length){var v=new Kg,z=new Jg;var H=Vd(z,2,wd(a));var D=ke(v,[H]);n=new Dg;var S=b.rate;$d(n,1,Eg,kd(!S||S<
.1||S>10?1:S));var Rf=b.pitch;Vd(n,6,kd(Rf?Math.pow(2,(Rf-1)*20/12):1));b.volume!==void 0&&b.volume>=0&&(c.gainNode.gain.value=Math.min(Math.max(b.volume,0),1));w=new Rg;var fd=new Lg;v=D;v=ie(v);$d(fd,2,Mg,v);v&&!Sc(v)&&Sd(fd.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows);var ph=ke(w,[fd]);var qh=new Fg;var rh=je(qh,3,n);var sh=je(ph,2,rh);var th=new Tg;var uh=je(th,2,sh);var gd=Array.from(new Uint8Array(Ug(uh))),vh=c.voiceNameToSpeakerName[m],wh=new Lf;var xh=Vd(wh,1,wd(vh));var hd=Cg(xh),
id=c.mainModule._malloc(gd.length);c.mainModule.HEAPU8.set(gd,id);var jd=c.mainModule._malloc(hd.length);c.mainModule.HEAPU8.set(hd,jd);var yh=c.mainModule._GoogleTtsInitBuffered(id,jd,gd.length,hd.length);c.mainModule._free(id);c.mainModule._free(jd);if(!yh)throw Error("Failed to initialize buffered synthesis.");jh(c)}}catch(Tf){return h=Tf instanceof Error?Tf.message:"",k.return(Promise.reject(Error("Synthesis failed with "+h)))}k.nextAddress=0}})};
function Yg(a){return a.JSC$3934_context.audioWorklet.addModule("../streaming_worklet_processor.js").then(function(){a.streamingNode=new AudioWorkletNode(a.JSC$3934_context,"streaming-worklet-processor");a.streamingNode.port.onmessage=function(b){a.utterance&&!a.isReadingMoreSamples&&b.data.type==="empty"&&(kh(a,{type:"end",charIndex:a.utterance.length}),a.onStop(!1))};a.gainNode.connect(a.JSC$3934_context.destination)})}
function ih(a,b){b=a.textEncoder.encode(b+"\x00");var c=a.mainModule._malloc(b.length);a.mainModule.HEAPU8.set(b,c);return c}
function jh(a){var b=setTimeout(function(){a.isReadingMoreSamples=!0;var c=a.mainModule,d=c._GoogleTtsReadBuffered();if(d===-1)kh(a,{type:"error"}),dh(a);else{for(var e=c._GoogleTtsGetTimepointsCount(),f=0;f<e;f++)lh(a,{audioDeltaMillis:c._GoogleTtsGetTimepointsTimeInSecsAtIndex(f)*1E3,charIndex:Number(c._GoogleTtsGetTimepointsCharIndexAtIndex(f)),length:Number(c._GoogleTtsGetTimepointsCharLengthAtIndex(f))});f=c._GoogleTtsGetEventBufferPtr();e=c._GoogleTtsGetEventBufferLen();c=new Uint8Array(c.HEAPU8.buffer,
f,e);c=Bg(c.slice(0,e));d=d===0;e=c.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows;fe(e,e[C]|0)!==void 0?mh(a,c,d):nh(a,null);d?dh(a):jh(a)}},0);a.scheduledReadingEvents.push(b)}function dh(a){a.isReadingMoreSamples=!1;a.mainModule._GoogleTtsFinalizeBuffered()}function eh(a){for(;a.scheduledReadingEvents.length>0;)window.clearTimeout(a.scheduledReadingEvents.pop())}
function lh(a,b){var c=b.audioDeltaMillis,d=b.charIndex,e=b.length;d<0||c<=0||(a.audioPlaying?c<-100||(c<2?kh(a,{type:"word",charIndex:d,length:e}):(c=window.setTimeout(function(){a.audioPlaying?kh(a,{type:"word",charIndex:d,length:e}):a.timepointEventQueue.push(b)},c),a.scheduledTimepointEvents.push(c))):a.timepointEventQueue.push(b))}function gh(a){var b=a.timepointEventQueue;a.timepointEventQueue=[];b=q(b);for(var c=b.next();!c.done;c=b.next())lh(a,c.value)}
function mh(a,b,c){if(Kf(he(b))===24E3){var d;b=(d=Jf(he(b)))==null?void 0:new Uint8Array(Ob(d)||0);d=new Uint8Array(b);d=new Int16Array(d.buffer);d=Float32Array.from(d,function(e){return e/32768});oh(a,d,c)}}function oh(a,b,c){for(var d=a.lastPartialBuffer,e=a.lastPartialBufferLength,f=0,g=b.length;f<g;){var h=Math.min(128-e,g-f);d||(d=new Float32Array(128));d.set(b.subarray(f,f+h),e);f+=h;e+=h;e===128&&(nh(a,d),e=0,d=null)}e!==0&&(c?nh(a,d):(a.lastPartialBuffer=d,a.lastPartialBufferLength=e))}
function nh(a,b){for(b&&a.sampleBuffers.push(b);b=a.sampleBuffers.shift();)a.streamingNode.port.postMessage({command:"addBuffer",buffer:b}),a.playbackStarted||a.pausedByClient||fh(a)}function fh(a){a.streamingNode.connect(a.gainNode);a.JSC$3934_context.resume();a.audioPlaying=!0;a.playbackStarted=!0;kh(a,{type:"start",charIndex:0});gh(a)}function Zg(a,b){return t(function(c){return c.return(zh(a,b,!1))})}function $g(a,b){return t(function(c){return c.return(zh(a,b,!0))})}
function zh(a,b,c){var d,e,f;return t(function(g){switch(g.nextAddress){case 1:return d=ah(a,b),e=d.map(function(h){return hh(a,h.speakers[0].name,c)}),g.catchAddress_=2,r(g,Promise.all(e),4);case 4:f="installed";c&&ch(a);g.nextAddress=3;g.catchAddress_=0;break;case 2:qa(g),f=c?"failed":"notInstalled";case 3:return g.return(f)}})}
function ah(a,b){var c=b.toLowerCase();return c.includes("-")?a.voiceData.filter(function(d){var e;return((e=d.language)==null?void 0:e.toLowerCase())===c}):a.voiceData.filter(function(d){var e;return((e=d.language)==null?void 0:e.split("-")[0])===c})}
function Ah(a,b,c){var d,e,f,g,h,k,m,n,w,v;return t(function(z){if(!a.voiceNameToDependentVoiceId[b])return z.return(Promise.resolve());d=a.voiceNameToDependentVoiceId[b];f=q(Object.entries(a.voiceNameToId));for(g=f.next();!g.done;g=f.next())if(h=g.value,k=q(h),m=k.next().value,n=k.next().value,w=m,v=n,d===v){e=w;break}return e?z.return(hh(a,e,c)):z.return(Promise.reject(Error("No multivoice found for: "+b)))})}
function hh(a,b,c){var d,e,f,g,h,k;return t(function(m){switch(m.nextAddress){case 1:if(!a.mainModule)return m.return(Promise.reject(Error("WASM module not initialized.")));m.catchAddress_=2;return r(m,Ah(a,b,c),4);case 4:m.nextAddress=3;m.catchAddress_=0;break;case 2:return d=qa(m),m.return(Promise.reject(Error(""+d)));case 3:e=a.voiceNameToFileId[b];if(!e)return m.return(Promise.reject(Error("Invalid voice name: "+b)));f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");try{if(h=a.mainModule.FS.stat(g))return m.return(Promise.resolve())}catch(n){}k=
a.voiceNameToUrl[b];return c||k.indexOf("http")!==0?m.return(fetch(k).then(function(n){return n.ok?n.arrayBuffer():Promise.reject(Error("Failed to fetch voice from url: "+k))}).then(function(n){if(!n)return Promise.reject(Error("Failed to fetch voice from url: "+k));try{a.mainModule.FS.stat(f)}catch(H){a.mainModule.FS.mkdir(f)}a.mainModule.FS.stat(f);var w=ih(a,f),v=new Uint8Array(n),z=a.mainModule._malloc(v.length);a.mainModule.HEAPU8.set(v,z);n=a.mainModule._GoogleTtsInstallVoice(w,z,n.byteLength);
a.mainModule._free(w);a.mainModule._free(z);return n===1?Promise.resolve():Promise.reject(Error("Failed to install voice."))})):m.return(Promise.reject(Error("Not downloading remote voice because caller did not request it.")))}})}function kh(a,b){a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenTtsEventResponse",event:b})}
function Wg(a){var b,c;return t(function(d){if(d.nextAddress==1){if((b=a.mainModule)==null||!b.FS)throw Error("WASM FS not ready for IDBFS setup.");try{a.mainModule.FS.stat("/voices")}catch(e){a.mainModule.FS.mkdir("/voices")}d.catchAddress_=2;return r(d,new Promise(function(e,f){a.mainModule.FS.mount(a.mainModule.IDBFS,{},"/voices");a.mainModule.FS.syncfs(!0,function(g){g?f(g):e()})}),4)}if(d.nextAddress!=2)d.nextAddress=0,d.catchAddress_=0;else throw c=qa(d),c;})}
function Xg(a){var b,c,d;return t(function(e){switch(e.nextAddress){case 1:return e.catchAddress_=2,r(e,fetch("voices.json"),4);case 4:b=e.yieldResult;if(!b.ok)throw Error("Failed to fetch voices.json: "+b.statusText+" ("+b.status+")");return r(e,b.json(),5);case 5:c=e.yieldResult;a.voiceData=c;ch(a);e.nextAddress=0;e.catchAddress_=0;break;case 2:throw d=qa(e),d;}})}
function ch(a){a.voiceNameToUrl={};a.voiceNameToId={};a.voiceNameToFileId={};a.voiceNameToSpeakerName={};a.voiceNameToDependentVoiceId={};for(var b={},c=q(a.voiceData),d=c.next();!d.done;d=c.next()){d=d.value;for(var e=q(d.speakers),f=e.next();!f.done;f=e.next()){f=f.value;a.voiceNameToId[f.name]=d.id;a.voiceNameToFileId[f.name]=d.file_id;a.voiceNameToSpeakerName[f.name]=f.speaker;d.dependent_voice_id&&(a.voiceNameToDependentVoiceId[f.name]=d.dependent_voice_id);bh(a,d);a.voiceNameToUrl[f.name]=d.remote&&
d.unloaded?d.url:"/"+d.id+".zvoice";var g=d.id.split("-");if(g.length<2)throw Error("Unexpected voice id format: "+d.id);g=g[0]+"-"+g[1].toUpperCase();d.language=g;d.remote&&d.unloaded||(b[g]||(b[g]=[]),b[g].push(f.name))}}a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenVoicesResponse",voices:b})}function bh(a,b){try{a.mainModule.FS.stat(["/voices",b.file_id].join("/")),b.unloaded=!1}catch(c){b.unloaded=!0}}
ea.Object.defineProperties(Vg.prototype,{voices:{configurable:!0,enumerable:!0,get:function(){return this.voiceData}}});var Bh=new Vg;chrome.runtime.onMessage.addListener(function(a,b,c){a.type==="do-task"&&(console.info("Doing task",a),Bh.init(b.id).then(function(){Bh.mainModule?c({result:"Task completed"}):c({result:"Failed to load TTS WASM Module"})}));return!0});
chrome.runtime.onMessage.addListener(function(a,b,c){a.type==="getLanguageStatus"?Bh.onLanguageStatusRequest(a.lang).then(function(d){c(d)}):a.type==="installLanguage"?Bh.onInstallLanguageRequest(a.lang).then(function(d){c(d)}):a.type==="uninstallLanguage"&&Bh.onUninstallLanguageRequest(a.lang).then(function(d){c(d)});return!0});chrome.runtime.onMessage.addListener(function(a,b,c){a.type==="speak"&&(Bh.onSpeak(a.utterance,a.options),c({result:"Start speaking"}));return!0});
chrome.runtime.onMessage.addListener(function(a,b,c){a.type==="stop"?(Bh.onStop(!0),c({result:"Stopped speech"})):a.type==="pause"?(Bh.onPause(),c({result:"Paused speech"})):a.type==="resume"&&(Bh.onResume(),c({result:"Resumed speech"}));return!0});
